const DB='cartazes-db', VER=2; let db, products=[], posters=[], changes=[], newCount=0, gtinCount=0, deferredPrompt, html5QrCode=null, scannerRunning=false, lastScanned='';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('data'))d.createObjectStore('data')};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function get(k){return new Promise(res=>{const r=db.transaction('data').objectStore('data').get(k);r.onsuccess=()=>res(r.result)})}function set(k,v){return new Promise((res,rej)=>{const r=db.transaction('data','readwrite').objectStore('data').put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dec(v){if(v==null)return 0;let s=String(v).trim().replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');return Number(s)||0}
function splitCSV(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===';'&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out.map(x=>x.trim())}
function validGtin(v){const s=String(v??'').trim();return /^\d{8,14}$/.test(s)?s:null}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)throw Error('CSV vazio');const headers=splitCSV(lines[0]).map(x=>x.toUpperCase());const required=['PRO_COD','PRO_DESC','VENDA'];for(const x of required)if(!headers.includes(x))throw Error('Coluna obrigatória ausente: '+x);const idx=Object.fromEntries(headers.map((h,i)=>[h,i]));const map=new Map();for(const line of lines.slice(1)){const a=splitCSV(line), code=String(a[idx.PRO_COD]||'').trim();if(!code)continue;let p=map.get(code);if(!p){p={code,description:a[idx.PRO_DESC]||'',departmentCode:a[idx.DEP_COD]||'',department:a[idx.DEP_DESC]||'',categoryCode:a[idx.CAT_COD]||'',category:a[idx.CAT_DESC]||'',stock:dec(a[idx.QUANTIDADE]),price:dec(a[idx.VENDA]),cost:dec(a[idx.CUSTO]),margin:dec(a[idx.MARK_CALC]),gtins:[]};map.set(code,p)}const g=idx.GTIN!==undefined?validGtin(a[idx.GTIN]):null;if(g&&!p.gtins.includes(g))p.gtins.push(g)}return [...map.values()]}
async function importFile(file){try{toast('Processando CSV...');const text=new TextDecoder('windows-1252').decode(await file.arrayBuffer());const incoming=parseCSV(text);const old=new Map(products.map(p=>[p.code,p]));changes=[];newCount=0;for(const p of incoming){const prev=old.get(p.code);if(!prev)newCount++;else if(Math.abs(prev.price-p.price)>.001)changes.push({code:p.code,description:p.description,old:prev.price,current:p.price})}products=incoming;gtinCount=new Set(products.flatMap(p=>p.gtins||[])).size;await Promise.all([set('products',products),set('changes',changes),set('newCount',newCount),set('updatedAt',new Date().toISOString())]);updateUI();$('#importResult').classList.remove('hidden');$('#importResult').innerHTML=`<b>✅ Importação concluída</b><p><strong>${products.length.toLocaleString('pt-BR')}</strong> produtos únicos · <strong>${gtinCount.toLocaleString('pt-BR')}</strong> GTINs · ${newCount} novos · ${changes.length} preços alterados</p>`;toast('Base atualizada!')}catch(e){alert('Não foi possível importar: '+e.message)}}
function go(id){if(id!=='scanner')stopScanner();$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');if(id==='posters')renderPosters();if(id==='changes')renderChanges();if(id==='search')setTimeout(()=>$('#searchInput').focus(),80)}
function productCard(p){const added=posters.some(x=>x.code===p.code);return `<article class="product"><h3>${esc(p.description)}</h3><div class="meta">Cód. ${esc(p.code)} · ${esc(p.department||'Sem departamento')}</div><div class="meta">${esc(p.category||'')} · Estoque: ${p.stock.toLocaleString('pt-BR')}</div>${p.gtins?.length?`<div class="gtin">GTIN: ${esc(p.gtins[0])}${p.gtins.length>1?` <span>+${p.gtins.length-1}</span>`:''}</div>`:''}<div class="price">${money(p.price)}</div><button class="${added?'secondary added':'primary'}" onclick="addPoster('${esc(p.code)}')">${added?'✓ Já adicionado':'🏷️ Adicionar placa'}</button></article>`}
function search(){const q=$('#searchInput').value.trim().toLocaleLowerCase('pt-BR');if(q.length<2){$('#results').innerHTML='';return}const found=products.filter(p=>p.code.toLowerCase().includes(q)||p.description.toLocaleLowerCase('pt-BR').includes(q)||(p.gtins||[]).some(g=>g.includes(q))).slice(0,30);$('#results').innerHTML=found.map(productCard).join('')||'<p class="hint">Nenhum produto encontrado.</p>'}
function findByGtin(gtin){const g=String(gtin).replace(/\D/g,'');const found=products.filter(p=>(p.gtins||[]).includes(g));$('#scanResult').innerHTML=found.length?`${found.length>1?'<div class="warning">⚠️ Este GTIN está ligado a mais de um produto. Escolha o correto.</div>':''}${found.map(productCard).join('')}`:`<div class="card"><b>GTIN não encontrado</b><p>${esc(g)}</p><small>Confira se a base CSV está atualizada.</small></div>`;if(found.length)navigator.vibrate?.(80);return found.length}
async function startScanner(){
 if(!products.length){alert('Importe o CSV atualizado primeiro.');return}
 if(!window.Html5Qrcode){alert('O leitor de câmera não carregou. Verifique sua internet e atualize a página.');return}
 try{
  html5QrCode=html5QrCode||new Html5Qrcode('reader',{verbose:false});
  const formats=[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E,Html5QrcodeSupportedFormats.CODE_128,Html5QrcodeSupportedFormats.ITF];
  const width=Math.min(window.innerWidth-64,520); const qrWidth=Math.max(240,Math.min(width-30,380));
  await html5QrCode.start({facingMode:'environment'},{fps:12,qrbox:{width:qrWidth,height:150},aspectRatio:1.777778,formatsToSupport:formats,disableFlip:false},onScanSuccess,()=>{});
  scannerRunning=true;$('#scannerPlaceholder').hidden=true;$('#toggleCamera').textContent='⏹ Parar câmera';$('#cameraStatus').classList.add('ready');$('#cameraStatus').querySelector('b').textContent='Câmera ativa';$('#cameraStatus').querySelector('small').textContent='Centralize o código de barras dentro da área de leitura.';
 }catch(e){console.error(e); scannerRunning=false; alert('Não foi possível abrir a câmera. No iPhone, permita o acesso à câmera em Ajustes/Safari e tente novamente. O site precisa estar em HTTPS.')}
}
function onScanSuccess(decodedText){const value=String(decodedText||'').replace(/\D/g,'');if(!value||value===lastScanned)return;lastScanned=value;setTimeout(()=>lastScanned='',1800);$('#gtinInput').value=value;const found=findByGtin(value);if(found){navigator.vibrate?.(80);toast('✓ Código lido: '+value);stopScanner()}}
async function stopScanner(){
 if(html5QrCode&&scannerRunning){try{await html5QrCode.stop();await html5QrCode.clear()}catch(e){console.warn(e)}}
 scannerRunning=false;const ph=$('#scannerPlaceholder');if(ph)ph.hidden=false;const b=$('#toggleCamera');if(b)b.textContent='📷 Iniciar câmera';const st=$('#cameraStatus');if(st){st.classList.remove('ready');st.querySelector('b').textContent='Leitura automática';st.querySelector('small').textContent='EAN/GTIN será identificado sem precisar digitar.'}
}
async function addPoster(code){if(posters.some(x=>x.code===code)){toast('Produto já está na lista');return}const p=products.find(x=>x.code===code);if(!p)return;posters.unshift({...p,addedAt:new Date().toISOString()});await set('posters',posters);updateUI();search();if($('#scanResult'))$('#scanResult').querySelectorAll('button').forEach(()=>{});toast('Placa adicionada')}
async function removePoster(code){posters=posters.filter(x=>x.code!==code);await set('posters',posters);updateUI();renderPosters()}
function renderPosters(){$('#posterList').innerHTML=posters.map(p=>`<div class="poster"><div class="info"><b>${esc(p.description)}</b><small>${esc(p.code)} · ${money(p.price)}</small></div><button class="remove" onclick="removePoster('${esc(p.code)}')">✕</button></div>`).join('')||'<div class="card"><p>Nenhuma placa adicionada ainda.</p></div>'}
function renderChanges(){$('#changeList').innerHTML=changes.map(c=>`<div class="change"><b>${esc(c.description)}</b><div class="meta">Cód. ${esc(c.code)}</div><div class="prices">${money(c.old)} → <span class="${c.current>c.old?'up':'down'}">${money(c.current)}</span></div><button class="secondary" onclick="addPoster('${esc(c.code)}')">🏷️ Solicitar placa</button></div>`).join('')||'<div class="card"><p>Nenhuma alteração de preço na última importação.</p></div>'}
function updateUI(){get('updatedAt').then(v=>$('#baseInfo').textContent=v?`Base: ${new Date(v).toLocaleString('pt-BR')}`:'Nenhuma base importada');gtinCount=new Set(products.flatMap(p=>p.gtins||[])).size;$('#sProducts').textContent=products.length.toLocaleString('pt-BR');$('#sGtins').textContent=gtinCount.toLocaleString('pt-BR');$('#sPosters').textContent=posters.length;$('#posterCount').textContent=posters.length;$('#sChanged').textContent=changes.length}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function init(){await openDB();products=await get('products')||[];posters=await get('posters')||[];changes=await get('changes')||[];newCount=await get('newCount')||0;updateUI();$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#csvInput').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('#searchInput').oninput=search;$('#clearSearch').onclick=()=>{$('#searchInput').value='';search();$('#searchInput').focus()};$('#toggleCamera').onclick=()=>scannerRunning?stopScanner():startScanner();$('#gtinSearch').onclick=()=>findByGtin($('#gtinInput').value);$('#gtinInput').onkeydown=e=>{if(e.key==='Enter')findByGtin(e.target.value)};$('#copyCodes').onclick=async()=>{try{await navigator.clipboard.writeText(posters.map(p=>p.code).join('\n'));toast('Códigos copiados')}catch{toast('Não foi possível copiar')}};$('#exportTxt').onclick=()=>download('placas.txt',posters.map(p=>`${p.code}\t${p.description}\t${money(p.price)}`).join('\n'));$('#exportCsv').onclick=()=>download('placas.csv','PRO_COD;PRO_DESC;GTIN;VENDA\n'+posters.map(p=>`${p.code};"${p.description.replace(/"/g,'""')}";${p.gtins?.[0]||''};${p.price.toFixed(2).replace('.',',')}`).join('\n'),'text/csv');$('#clearPosters').onclick=async()=>{if(confirm('Limpar toda a lista de placas?')){posters=[];await set('posters',posters);updateUI();renderPosters()}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};document.addEventListener('visibilitychange',()=>{if(document.hidden)stopScanner()})}
init();
