const DB='cartazes-db', VER=1; let db, products=[], posters=[], changes=[], newCount=0, deferredPrompt;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('data'))d.createObjectStore('data')};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function get(k){return new Promise(res=>{const r=db.transaction('data').objectStore('data').get(k);r.onsuccess=()=>res(r.result)})}function set(k,v){return new Promise((res,rej)=>{const r=db.transaction('data','readwrite').objectStore('data').put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dec(v){if(v==null)return 0;let s=String(v).trim().replace(/\s/g,''); if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');return Number(s)||0}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)throw Error('CSV vazio');const headers=lines[0].split(';').map(x=>x.trim().replace(/^"|"$/g,''));const required=['PRO_COD','PRO_DESC','VENDA'];for(const x of required)if(!headers.includes(x))throw Error('Coluna obrigatória ausente: '+x);const idx=Object.fromEntries(headers.map((h,i)=>[h,i]));return lines.slice(1).map(line=>{const a=line.split(';').map(x=>x.trim().replace(/^"|"$/g,''));return {code:a[idx.PRO_COD]||'',description:a[idx.PRO_DESC]||'',departmentCode:a[idx.DEP_COD]||'',department:a[idx.DEP_DESC]||'',categoryCode:a[idx.CAT_COD]||'',category:a[idx.CAT_DESC]||'',stock:dec(a[idx.QUANTIDADE]),price:dec(a[idx.VENDA]),cost:dec(a[idx.CUSTO]),margin:dec(a[idx.MARK_CALC])}}).filter(p=>p.code)}
async function importFile(file){try{toast('Processando CSV...');const buf=await file.arrayBuffer();const text=new TextDecoder('windows-1252').decode(buf);const incoming=parseCSV(text);const old=new Map(products.map(p=>[p.code,p]));changes=[];newCount=0;for(const p of incoming){const prev=old.get(p.code);if(!prev)newCount++;else if(Math.abs(prev.price-p.price)>.001)changes.push({code:p.code,description:p.description,old:prev.price,current:p.price})}products=incoming;await set('products',products);await set('changes',changes);await set('newCount',newCount);await set('updatedAt',new Date().toISOString());updateUI();$('#importResult').classList.remove('hidden');$('#importResult').innerHTML=`<b>✅ Importação concluída</b><p>${products.length.toLocaleString('pt-BR')} produtos · ${newCount} novos · ${changes.length} preços alterados</p>`;toast('Base atualizada!')}catch(e){alert('Não foi possível importar: '+e.message)}}
function go(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');if(id==='posters')renderPosters();if(id==='changes')renderChanges();if(id==='search')setTimeout(()=>$('#searchInput').focus(),80)}
function search(){const q=$('#searchInput').value.trim().toLocaleLowerCase('pt-BR');if(q.length<2){$('#results').innerHTML='';return}const found=products.filter(p=>p.code.toLowerCase().includes(q)||p.description.toLocaleLowerCase('pt-BR').includes(q)).slice(0,30);$('#results').innerHTML=found.map(p=>`<article class="product"><h3>${esc(p.description)}</h3><div class="meta">Cód. ${esc(p.code)} · ${esc(p.department||'Sem departamento')}</div><div class="meta">Estoque: ${p.stock.toLocaleString('pt-BR')}</div><div class="price">${money(p.price)}</div><button class="${posters.some(x=>x.code===p.code)?'secondary added':'primary'}" onclick="addPoster('${esc(p.code)}')">${posters.some(x=>x.code===p.code)?'✓ Já adicionado':'🏷️ Adicionar placa'}</button></article>`).join('')||'<p class="hint">Nenhum produto encontrado.</p>'}
async function addPoster(code){if(posters.some(x=>x.code===code)){toast('Produto já está na lista');return}const p=products.find(x=>x.code===code);if(!p)return;posters.unshift({...p,addedAt:new Date().toISOString()});await set('posters',posters);updateUI();search();toast('Placa adicionada')}
async function removePoster(code){posters=posters.filter(x=>x.code!==code);await set('posters',posters);updateUI();renderPosters()}
function renderPosters(){ $('#posterList').innerHTML=posters.map(p=>`<div class="poster"><div class="info"><b>${esc(p.description)}</b><small>${esc(p.code)} · ${money(p.price)}</small></div><button class="remove" onclick="removePoster('${esc(p.code)}')">✕</button></div>`).join('')||'<div class="card"><p>Nenhuma placa adicionada ainda.</p></div>'}
function renderChanges(){ $('#changeList').innerHTML=changes.map(c=>`<div class="change"><b>${esc(c.description)}</b><div class="meta">Cód. ${esc(c.code)}</div><div class="prices">${money(c.old)} → <span class="${c.current>c.old?'up':'down'}">${money(c.current)}</span></div><button class="secondary" onclick="addPoster('${esc(c.code)}')">🏷️ Solicitar placa</button></div>`).join('')||'<div class="card"><p>Nenhuma alteração de preço na última importação.</p></div>'}
function updateUI(){const dt=localStorage.getItem('dummy');get('updatedAt').then(v=>$('#baseInfo').textContent=v?`Base: ${new Date(v).toLocaleString('pt-BR')}`:'Nenhuma base importada');$('#sProducts').textContent=products.length.toLocaleString('pt-BR');$('#sPosters').textContent=posters.length;$('#posterCount').textContent=posters.length;$('#sChanged').textContent=changes.length;$('#sNew').textContent=newCount}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function init(){await openDB();products=await get('products')||[];posters=await get('posters')||[];changes=await get('changes')||[];newCount=await get('newCount')||0;updateUI();$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#csvInput').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);$('#searchInput').oninput=search;$('#clearSearch').onclick=()=>{$('#searchInput').value='';search();$('#searchInput').focus()};$('#copyCodes').onclick=async()=>{await navigator.clipboard.writeText(posters.map(p=>p.code).join('\n'));toast('Códigos copiados')};$('#exportTxt').onclick=()=>download('placas.txt',posters.map(p=>`${p.code}\t${p.description}\t${money(p.price)}`).join('\n'));$('#exportCsv').onclick=()=>download('placas.csv','PRO_COD;PRO_DESC;VENDA\n'+posters.map(p=>`${p.code};"${p.description.replace(/"/g,'""')}";${p.price.toFixed(2).replace('.',',')}`).join('\n'),'text/csv');$('#clearPosters').onclick=async()=>{if(confirm('Limpar toda a lista de placas?')){posters=[];await set('posters',posters);updateUI();renderPosters()}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}}}
init();
